# Generated by Django 6.0.1 on 2026-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_airesponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
